# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lgtrp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Date'),
        ),
    ]
